name: Cerberus Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy Stack
        env:
          # Domain Variables
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          AUTHELIA_SUBDOMAIN: ${{ vars.AUTHELIA_SUBDOMAIN }}
          LLDAP_SUBDOMAIN: ${{ vars.LLDAP_SUBDOMAIN }}
          LLDAP_LDAP_BASE_DN: ${{ vars.LLDAP_LDAP_BASE_DN }}
          
          # Secrets
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          STORAGE_ENCRYPTION_KEY: ${{ secrets.STORAGE_ENCRYPTION_KEY }}
          LLDAP_JWT_SECRET: ${{ secrets.LLDAP_JWT_SECRET }}
          LLDAP_KEY_SEED: ${{ secrets.LLDAP_KEY_SEED }}
          LLDAP_LDAP_USER_PASS: ${{ secrets.LLDAP_LDAP_USER_PASS }}
          LLDAP_LDAP_USER_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh "cerberus" docker-compose.yml docker-compose.prod.yml