name: Cerberus Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Stack
        env:
          # Domain Variables
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          AUTHELIA_SUBDOMAIN: ${{ vars.AUTHELIA_SUBDOMAIN }}
          
          # Secrets
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          STORAGE_ENCRYPTION_KEY: ${{ secrets.STORAGE_ENCRYPTION_KEY }}
        run: |
          chmod +x start.sh
          ./start.sh